GET http://localhost:8085/api/shedules

###

GET http://localhost:8085/api/shedules/67bccd4a88db04f2ffda2e9
###

POST http://localhost:8085/api/shedules
Content-Type: application/json

###

POST http://localhost:8085/api/shedules/slots/single
Content-Type: application/json

{
    "sheduleId": "67bccbc23f59f6e7d409460c",
    "startDateTime": "2016-11-26T08:00",
    "durationInMinutes": 15
}
  
###

POST http://localhost:8085/api/shedules/slots/many
Content-Type: application/json

{
    "sheduleId": "67bccbc23f59f6e7d409460c",
    "startDateTime": "1985-11-27T08:00",
    "durationInMinutes": 15,
    "betweenInervalInMinutes": 5,
    "slotsQuantity":5
}
  