GET http://localhost:8085/api/shedules

###

GET http://localhost:8085/api/shedules/67bde3b1795bef5891f4c3ec
###

POST http://localhost:8085/api/shedules
Content-Type: application/json

###

POST http://localhost:8085/api/shedules/slots/single
Content-Type: application/json

{
    "sheduleId": "67bde3b1795bef5891f4c3ec",
    "startDateTime": "2015-12-26T08:00",
    "durationInMinutes": 15
}
  
###

POST http://localhost:8085/api/shedules/slots/group
Content-Type: application/json

{
    "sheduleId": "67bde3b1795bef5891f4c3ec",
    "startDateTime": "1985-11-27T08:00",
    "durationInMinutes": 15,
    "betweenInervalInMinutes": 5,
    "slotsQuantity":5
}
  