GET http://localhost:8085/api/shedules

###

POST http://localhost:8085/api/shedules
Content-Type: application/json

###

POST http://localhost:8085/api/shedules/slots/single
Content-Type: application/json

{
    "sheduleId": "67bcbf1af32c675e089ebc99",
    "startDateTime": "2015-11-26T08:00",
    "durationInMinutes": 15
}
  
###

POST http://localhost:8085/api/shedules/slots/many
Content-Type: application/json

{
    "sheduleId": "67bcbf1af32c675e089ebc99",
    "startDateTime": "2015-11-26T08:00",
    "durationInMinutes": 15,
    "betweenInervalInMinutes": 5,
    "slotsQuantity":5
}
  