GET http://localhost:8085/api/shedules

###

POST http://localhost:8085/api/shedules
Content-Type: application/json

###

POST http://localhost:8085/api/shedules/slots/single
Content-Type: application/json

{
    "sheduleId": "67ae19385d401c1ea1eceec5",
    "startDateTime": "1985-12-23T08:45",
    "durationInMinutes": 15
}
  
###

POST http://localhost:8085/api/shedules/slots/many
Content-Type: application/json

{
    "sheduleId": "67ae19385d401c1ea1eceec5",
    "startDateTime": "1985-12-23T12:00",
    "durationInMinutes": 15,
    "betweenInervalInMinutes": 5,
    "slotsQuantity":5
}
  