POST http://localhost:8085/api/branchs
Content-Type: application/json

{
  "name": "Sucursal 24",
  "location": {
    "street": "Avenida Principal 456",
    "streeNumber": "456",
    "floor": "3",
    "apartment": "B",
    "city": "Ciudad Ejemplo",
    "postalCode": "98765",
    "state": "Estado Ejemplo",
    "country": "País Ejemplo",
    "latitude": 19.432608,
    "longitude": -99.133209
  }
}

###
GET http://localhost:8085/api/branchs/67c0a48c715f5ce479202332

###
GET http://localhost:8085/api/branchs

###
GET http://localhost:8085/api/branchs?ids=67c090f2113c0a53c768ebc4,67c09114113c0a53c768ebc8
###

DELETE http://localhost:8085/api/branchs?ids=67c090f2113c0a53c768ebc4,67c09114113c0a53c768ebc8


###

PUT http://localhost:8085/api/branchs/67c0a48c715f5ce479202332
Content-Type: application/json

{
  "name": "Sucursal 2a4",
  "location": {
    "street": "Avenida Principal 456",
    "streeNumber": "456",
    "floor": "3",
    "apartment": "B",
    "city": "Ciudad Ejemplo",
    "postalCode": "98765",
    "state": "Estado Ejemplo",
    "country": "País Ejemplo",
    "latitude": 19.432608,
    "longitude": -99.133209
  }
}