POST http://localhost:8085/api/bookings
Content-Type: application/json

{
  "customerId": "67bf64e11da11acc35baf675",
  "note":"nosdsdsta"  
}

###
POST http://localhost:8085/api/bookings
Content-Type: application/json

{
  
  "note":"Booking con customer vacio"  
}



###

GET http://localhost:8085/api/bookings

###

GET http://localhost:8085/api/bookings/67bf650b1da11acc35baf678
###

PUT http://localhost:8085/api/bookings/67bf650b1da11acc35baf678
Content-Type: application/json

{
    "status": "confirmed"
}

###
DELETE http://localhost:8085/api/bookings?ids=67bf34492527ba2fc292e688,67bf2eb6dcdc2ef53c4ac4ae